name: console_project
description: A sample command-line application.
version: 1.0.0


environment:
  sdk: '>=2.12.0 <3.0.0'

# Add regular dependencies here.
dependencies:
   dart_console: ^1.0.0
   riverpod: ^2.0.0
  # path: ^1.8.0

  

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
